[[navbar]]
name = "COLab"
url = "https://colabnews.co/"
weight = 1

[[navbar]]
name = "Suggest a Source"
url = "http://bit.ly/AmplifyColorado"
weight = 2
post = "_blank"

[[navbar]]
name = "Contact Us"
url = "mailto:todo@example.com"
weight = 3

[[mobile]]
name = "Home"
url = "/"
weight = 1

[[mobile]]
name = "COLab"
url = "https://colabnews.co/"
weight = 2

[[mobile]]
name = "Suggest a Source"
url = "http://bit.ly/AmplifyColorado"
weight = 3
post = "_blank"

[[mobile]]
name = "Contact Us"
url = "mailto:todo@example.com"
weight = 4

[[mobile]]
name = "Donate"
url = "http://colab.fundjournalism.org/donate"
weight = 5


[[footer]]
name = "Home"
url = "https://colabnews.co/"
weight = 1

[[footer]]
name = "About Us"
url = "https://colabnews.co/mission-and-vision/"
weight = 2

[[footer]]
name = "Contact"
url = "mailto:todo@example.com"
weight = 3

[[footer]]
name = "Donate"
url = "http://colab.fundjournalism.org/donate"
weight = 4


[[follow]]
name = "FAQs"
url = "https://colabnews.co/amplify-colorado/"
weight = 1

[[follow]]
name = "Suggest a Source"
url = "http://bit.ly/AmplifyColorado"
weight = 2
post = "_blank"

[[follow]]
name = "Contact"
url = "mailto:todo@example.com"
weight = 3
