[[navbar]]
name = "RCSA"
url = "https://rescorp.org/"
weight = 1

[navbar.params]
image = "img/logos/rcsa_logo.png"

[[navbar]]
name = "Contact Us"
url = "mailto:hiddenfigs@googlegroups.com"
weight = 2

[[navbar]]
name = "About Us"
url = "/about"
weight = 2

[[mobile]]
name = "Home"
url = "/"
weight = 1

[[mobile]]
name = "RCSA"
url = "https://rescorp.org/"
weight = 2

[[mobile]]
name = "Add your info"
url = "https://forms.gle/ZRopiyBevpXu9D459"
weight = 3
post = "_blank"

[[mobile]]
name = "Contact Us"
url = "mailto:hiddenfigs@googlegroups.com"
weight = 4

[[footer]]
name = "Home"
url = "https://rescorp.org/"
weight = 1

[[footer]]
name = "About CSC"
url = "https://rescorp.org/cottrell-scholars/cottrell-scholars-collaborative"
weight = 2

[[follow]]
name = "About Us"
url = "/about"
weight = 2

[[follow]]
name = "Add your info"
url = "https://forms.gle/ZRopiyBevpXu9D459"
weight = 2
post = "_blank"

[[follow]]
name = "Contact"
url = "mailto:hiddenfigs@googlegroups.com"
weight = 3