baseURL = "https://amplifycolorado.colabnews.co/"
languageCode = "en-us"
title = ""
enableRobotsTXT = true
enableGitInfo = true
rssLimit = 50
Paginate = 25

googleAnalytics = 'G-0N3FRVSW3G'
buildFuture = true

[params]
  favicon = "/img/logos/hiddenfigs_logo.png"
  touch-icon = "/img/logos/hiddenfigs_logo.png"
[taxonomies]
  researchAreas = "researchAreas"
  relevantCourses = "relevantCourses"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
  definitionList = false
  footnote = false
  linkify = false
  strikethrough = false
  table = false
  taskList = false
  typographer = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["html"]
  section = ["html"]
  taxonomy = ["html"]
  term = ["html"]

[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[minify]
  minifyOutput = true

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static/img/uploads"
target = "assets/img/uploads"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "pages"
target = "content"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/svgs"
target = "assets/@fontawesome"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
