[build]
base = ""
command = "yarn build:prod"
publish = "public"

[build.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"
NODE_VERSION = "14"
GO_IMPORT_PATH = "github.com/spotlightpa/sourcesdb"
GO111MODULE = "on"

[context.deploy-preview]
command = "yarn build:stage"

[context.branch-deploy]
command = "yarn build:stage"
