media_folder: static/img/uploads
public_folder: /img/uploads

site_url: https://sources.spotlightpa.org
display_url: https://sources.spotlightpa.org
logo_url: https://www.spotlightpa.org/img/logos/banner-share-5000.png

show_preview_links: true

backend:
  name: git-gateway
  branch: main

collections:
  - label: People
    label_singular: Person
    name: people
    folder: content/people
    format: json
    extension: md
    create: true
    slug: "{{name}}"
    preview_path: /people/
    identity_field: name
    editor:
      preview: false
    fields:
      - label: Full name
        hint: E.g. "John Jacob Jingleheimer Smith, IV"
        name: title
        widget: string
        required: true
      - label: Display name
        hint: E.g. "John Smith" (defaults to full name)
        name: linktitle
        widget: string
        required: false
      - label: Sortable name
        hint: E.g. "Smith, John Jacob Jingleheimer 4"
        name: full-name
        widget: string
        required: true
      - label: Email
        name: email
        widget: email
        required: false
      - label: "Headshot"
        name: "headshot"
        widget: "image"
        media_library:
          config:
            multiple: false
