media_folder: static/img/uploads
public_folder: /img/uploads

site_url: https://sources.spotlightpa.org
display_url: https://sources.spotlightpa.org
logo_url: https://www.spotlightpa.org/img/logos/capitol-moody-logo-500.jpeg

show_preview_links: true

backend:
  name: git-gateway
  branch: main

collections:
  - label: People
    label_singular: Person
    name: people
    folder: content/people
    format: json
    extension: md
    create: true
    slug: "{{title}}"
    preview_path: /people/{{slug}}/
    identity_field: title
    editor:
      preview: false
    fields:
      - label: Full name
        hint: E.g. "John Jacob Jingleheimer Schmidt, IV"
        name: title
        widget: string
        required: true
      - label: First name
        hint: E.g. "John Jacob"
        name: first
        widget: string
        required: true
      - label: Last name
        hint: E.g. "Schmidt"
        name: last
        widget: string
        required: true
      - label: Honorific
        hint: E.g. Dr., Prof., Mr., Ms., Mx.
        name: honorific
        widget: string
        required: false
      - label: Pronoun
        hint: E.g. "he/him," "she/her," "they/them"
        name: pronoun
        widget: string
        required: false
      - label: Title or Profession
        hint: E.g. Assistant Professor of Example Studies
        name: role
        widget: string
        required: false
      - label: Expertise
        name: expertise
        widget: list
        required: false
      - label: Keywords
        name: keywords
        widget: list
        required: false
      - label: Email
        name: email
        widget: email
        required: false
      - label: "Headshot"
        name: "images"
        widget: list
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - label: Website
        hint: Full URL with http://
        name: website
        widget: string
        required: false
      - label: Facebook
        hint: Just the username without http://facebook.com/
        name: facebook
        widget: string
        required: false
      - label: Twitter
        hint: Just the username without the @
        name: twitter
        widget: string
        required: false
      - label: Instagram
        hint: Just the username without the @
        name: instagram
        widget: string
        required: false
      - label: Location
        hint: City, state, e.g. "Philadelphia, Pa."
        name: location
        widget: string
        required: false
      - label: "Phone"
        hint: Just the digits
        name: phone
        widget: string
        required: false
      - label: Biography
        name: bio
        widget: markdown
        required: false
